version: '2'
services:
  elasticsearch-central:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: es1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - node.name=node-1
      - xpack.license.self_generated.type=trial
      - "xpack.security.enabled=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch-data:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: es2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - node.name=node-2
      - xpack.license.self_generated.type=trial
      - "xpack.security.enabled=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch-central:9200"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=Tkds4uQx2gjXjJ7Q7X8Y"
      - "XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-central
      - elasticsearch-data
    networks:
      - esnet
  fluentd:
    #image: fluent/fluentd:latest
    build: ./fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
    environment:
      - 'FLUENTD_CONF=fluentd.conf'
    volumes:
      - ./tmp/fluentd:/fluentd/log
      - ./etc:/fluentd/etc
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    driver: bridge
